name: paint_color_resolver
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.9.2
  flutter: 3.35.6
description: Paint Color Resolver is an application designed to help miniature and figurine painters achieve their desired colors by calculating optimal paint mixing ratios based on their available paint inventory.
dependencies:
  auto_route: ^10.1.2
  dart_mappable: ^4.6.1
  drift: ^2.28.2
  flutter:
    sdk: flutter
  flutter_color: ^2.1.0
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^3.0.3
  logging: ^1.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  shadcn_ui: ^0.37.4
  sqlite3_flutter_libs: ^0.5.40
dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  dart_mappable_builder: ^4.6.0
  drift_dev: ^2.28.3
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  test: ^1.26.2
  very_good_analysis: ^10.0.0
flutter:
  uses-material-design: true
