name: paint_color_resolver
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.10.0
  flutter: 3.41.0
description: Paint Color Resolver is an application designed to help miniature and figurine painters achieve their desired colors by calculating optimal paint mixing ratios based on their available paint inventory.
dependencies:
  auto_route: ^11.1.0
  dart_mappable: ^4.6.1
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_color: ^2.1.0
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^3.1.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  phosphor_flutter: ^2.0.2
  riverpod_annotation: ^4.0.0
  shadcn_ui: ^0.46.1
  sqlite3_flutter_libs: ^0.5.40
dev_dependencies:
  auto_route_generator: ^10.2.4
  build: ^4.0.4
  build_runner: ^2.7.1
  build_web_compilers: ^4.3.0
  dart_mappable_builder: ^4.6.0
  drift_dev: ^2.28.3
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.3
  test: ^1.26.2
  very_good_analysis: ^10.0.0
flutter:
  # uses-material-design: true  # No longer needed with shadcn_ui
